jobs:
  close:
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v4
      with:
        close-issue-message: This issue has been closed since it has been inactive
          for 3 weeks since it was marked as stale.
        days-before-issue-close: 21
        days-before-issue-stale: 21
        days-before-pr-close: -1
        days-before-pr-stale: -1
        exempt-issue-labels: timeless, suggestion, critical
        operations-per-run: 10000
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: stale
        stale-issue-message: This issue has been marked as stale because it has been
          inactive for 3 weeks. It will be closed if it remains inactive for another
          3 weeks.
name: Close Issues
on:
  repository_dispatch:
    types: trigger-ga___close_issues.yml
