jobs:
  label:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: github/issue-labeler@v3.0
      with:
        configuration-path: .github/config/labels.yml
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: 1
name: Label Issues
on:
  repository_dispatch:
    types: trigger-ga___label_issues.yml
